In [24]:
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import datasets

In [25]:
data=pd.read_csv('0000000000002429_training_titanic_x_y_train.csv')
data

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [26]:
def f(s):
    if s=='male':
        return 0
    else:
        return 1
data['Sex']=data.Sex.apply(f)

In [27]:
data

Pclass                                            Name  Sex   Age  SibSp  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)    1  29.0      1   
1         3               Williams, Mr. Howard Hugh "Harry"    0   NaN      0   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    0  39.0      0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)    1  29.0      0   
4         3                          Sutehall, Mr. Henry Jr    0  25.0      0   
..      ...                                             ...  ...   ...    ...   
663       2                             Ilett, Miss. Bertha    1  17.0      0   
664       3                        Morrow, Mr. Thomas Rowan    0   NaN      0   
665       3                                   Bing, Mr. Lee    0  32.0      0   
666       3                     Strandberg, Miss. Ida Sofia    1  22.0      0   
667       3                  Murphy, Miss. Katherine "Kate"    1   NaN      1   

     Parch           Ticket     Fare Cabin Embarked  Survived  
0        0           228414  26.0000   NaN        S         1  
1        0         A/5 2466   8.0500   NaN        S         0  
2        0           250655  26.0000   NaN        S         0  
3        4           349909  21.0750   NaN        S         0  
4        0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...              ...      ...   ...      ...       ...  
663      0       SO/C 14885  10.5000   NaN        S         1  
664      0           372622   7.7500   NaN        Q         0  
665      0             1601  56.4958   NaN        S         1  
666      0             7553   9.8375   NaN        S         0  
667      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [28]:
data=data.iloc[:,[0,2,4,5,7,10]]

In [29]:
data=np.array(data)
data

array([[ 2.    ,  1.    ,  1.    ,  0.    , 26.    ,  1.    ],
       [ 3.    ,  0.    ,  0.    ,  0.    ,  8.05  ,  0.    ],
       [ 2.    ,  0.    ,  0.    ,  0.    , 26.    ,  0.    ],
       ...,
       [ 3.    ,  0.    ,  0.    ,  0.    , 56.4958,  1.    ],
       [ 3.    ,  1.    ,  0.    ,  0.    ,  9.8375,  0.    ],
       [ 3.    ,  1.    ,  1.    ,  0.    , 15.5   ,  1.    ]])

In [30]:
clf=LogisticRegression()

In [31]:
x=data[:,:-1]
y=data[:,-1]
scaler=preprocessing.StandardScaler()
scaler.fit(x)
x=scaler.transform(x)
x

array([[-0.35668092,  1.33108386,  0.43682178, -0.47676762, -0.13391404],
       [ 0.84666683, -0.75126747, -0.48951775, -0.47676762, -0.5302759 ],
       [-0.35668092, -0.75126747, -0.48951775, -0.47676762, -0.13391404],
       ...,
       [ 0.84666683, -0.75126747, -0.48951775, -0.47676762,  0.53947717],
       [ 0.84666683,  1.33108386, -0.48951775, -0.47676762, -0.49080533],
       [ 0.84666683,  1.33108386,  0.43682178, -0.47676762, -0.36576917]])

In [32]:
clf.fit(x,y)

LogisticRegression()

In [36]:
clf.score(x,y)

0.7904191616766467

In [37]:
test=pd.read_csv('0000000000002429_test_titanic_x_test.csv')
test

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [38]:
def f(s):
    if s=='male':
        return 0
    else:
        return 1
test['Sex']=test.Sex.apply(f)

In [39]:
test

Pclass                                               Name  Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    0   8.0   
1         1                        Leader, Dr. Alice (Farnham)    1  49.0   
2         3                            Kilgannon, Mr. Thomas J    0   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...    1  24.0   
4         1                          McGough, Mr. James Robert    0  36.0   
..      ...                                                ...  ...   ...   
218       3                        Lindqvist, Mr. Eino William    0  20.0   
219       1                  Butt, Major. Archibald Willingham    0  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...    1  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    0  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    0  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

In [41]:
test=test.iloc[:,[0,2,4,5,7]]

In [42]:
test=np.array(test)
test

array([[  2.    ,   0.    ,   1.    ,   1.    ,  36.75  ],
       [  1.    ,   1.    ,   0.    ,   0.    ,  25.9292],
       [  3.    ,   0.    ,   0.    ,   0.    ,   7.7375],
       ...,
       [  1.    ,   1.    ,   1.    ,   0.    , 108.9   ],
       [  3.    ,   0.    ,   0.    ,   0.    ,   6.45  ],
       [  2.    ,   0.    ,   0.    ,   2.    ,  26.    ]])

In [43]:
xtest=scaler.transform(x)
xtest

array([[-3.19258759,  2.02051676, -0.08487246, -1.03500776, -0.71098852],
       [-1.74454179, -2.31567028, -0.94297738, -1.03500776, -0.71974076],
       [-3.19258759, -2.31567028, -0.94297738, -1.03500776, -0.71098852],
       ...,
       [-1.74454179, -2.31567028, -0.94297738, -1.03500776, -0.69611907],
       [-1.74454179,  2.02051676, -0.94297738, -1.03500776, -0.71886919],
       [-1.74454179,  2.02051676, -0.08487246, -1.03500776, -0.71610821]])

In [46]:
res=clf.predict(xtest)

In [48]:
np.savetxt('logistic.csv',res,fmt="%.2f")